### PR TITLE
Fix/sequelize

### LINKED ISSUE #15: Switch db interactions to Sequalize

### PR DESCRIPTION
**Pull request by kris-krsh02**
All current features working with sequelize.

### CODE REVIEW

File: server.js [hunk 1]
```diff
@@ -12,49 +11,56 @@ const app = express();
...
   }
+
+  await db.sequelize.sync({ force: false });
 };
 
-// Call the function to test the DB connection
-testDbConnection();
+// startDB();
+// setTimeout(() => {
+//   console.log("10 seconds have passed.");
```
Comment (AcidicMoss) [inline server.js:56]: remove or un comment this

**Review by AcidicMoss — APPROVED** [review]
looks good i left one comment as you left some commented out code in the server.js file
